USE Estimates
DECLARE @FRDATE AS DATETIME, @TODATE AS DATETIME

SET @FRDATE = '2023-10-01 00:00:00.000'
SET @TODATE = '2023-10-30 23:59:59.999' 

IF OBJECT_ID ('TEMPDB..#GYANCAGR') IS NOT NULL DROP TABLE #GYANCAGR
SELECT DISTINCT ED.VERSIONID,ED.FEEDFILEID,ED.COMPANYID,DBO.FORMATPERIODID_FN(EP.ESTIMATEPERIODID) AS PPEO,EDND.DATAITEMID,DBO.DATAITEMNAME_FN (EDND.DATAITEMID) AS DATAITEMNAME,
ED.EFFECTIVEDATE,EDND.TODATE,ED.RESEARCHCONTRIBUTORID,EDND.DATAITEMVALUE,EDND.UNITSID,EDND.CURRENCYID,ED.PARENTFLAG,EDND.LASTMODIFIEDUTCDATETIME INTO #GYANCAGR FROM ESTIMATEDETAIL_TBL ED
INNER JOIN ESTIMATEDETAILNUMERICDATA_TBL EDND (NOLOCK) ON ED.ESTIMATEDETAILID = EDND.ESTIMATEDETAILID
INNER JOIN EstimatesCompanyTier_tbl ET (NOLOCK) ON ET.companyId = ED.companyId
INNER JOIN ESTIMATEPERIOD_TBL EP (NOLOCK) ON EP.ESTIMATEPERIODID = ED.ESTIMATEPERIODID
WHERE EDND.DATAITEMID IN (21629,22498,22499)
AND EDND.LASTMODIFIEDUTCDATETIME + '5:30' >= @FRDATE 
AND EDND.LASTMODIFIEDUTCDATETIME + '5:30' <= @TODATE
AND ED.VERSIONID IS NULL

---SELECT * FROM #GYANCAGR

IF OBJECT_ID ('TEMPDB..#GYANFEEDFY0') IS NOT NULL DROP TABLE #GYANFEEDFY0
SELECT DISTINCT fd.feedFileId,fd.feedDataPointId,CASE WHEN TRY_CAST(fd.feedDataPointValue AS DECIMAL(10, 2)) IS NOT NULL THEN TRY_CAST(fd.feedDataPointValue AS DECIMAL(10, 2)) WHEN TRY_CONVERT(DECIMAL(10, 2), fd.feedDataPointValue) IS NOT NULL THEN TRY_CONVERT(DECIMAL(10, 2), fd.feedDataPointValue) ELSE NULL END AS feedDataPointValue,
fdp.feedDataPointName,fdp.feedDataPointDescription,fdpm.ciqId,fdpm.companyId,gc.LASTMODIFIEDUTCDATETIME, 
fdpm.tradingItemId,fdpm.accountingStandardId INTO #GYANFEEDFY0 FROM Estimatesfeed.[dbo].[feedData_tbl] fd
INNER JOIN Estimatesfeed.dbo.feeddatapoint_tbl fdp (NOLOCK) ON fdp.feedDataPointId=fd.feedDataPointId
INNER JOIN Estimatesfeed.[dbo].[FeedDataPointGroup_tbl] fdpg ON fdpg.feedDataPointGroupId=fdp.feedDataPointGroupId AND fdpg.feedId=fdp.feedId
INNER JOIN Estimatesfeed.dbo.FeedDataPointMap_tbl fdpm (NOLOCK) ON fdpm.feedDataPointId=fdp.feedDataPointId
INNER JOIN Estimatesfeed.[dbo].[FeedProcessEntityDetail_tbl] fped (NOLOCK) ON fped.companyId=fdpm.companyId AND fd.feedDataPointId=fped.feedDataPointId
INNER JOIN Estimatesfeed.[dbo].[FeedProcessEntity_tbl] fpe ON fped.feedProcessEntityId=fpe.feedProcessEntityId
INNER JOIN #GYANCAGR gc (NOLOCK) ON gc.feedFileId=fd.feedFileId AND gc.companyId=fdpm.companyId AND gc.dataItemValue=fd.feedDataPointValue
WHERE fdpm.ciqId IN (21634,21635,21650,21649)
AND gc.LASTMODIFIEDUTCDATETIME + '5:30' >= @FRDATE 
AND gc.LASTMODIFIEDUTCDATETIME + '5:30' <= @TODATE
AND fd.feedDataPointValue IS NOT NULL
AND fdp.endDate>GETDATE()
AND (fdp.feedDataPointName like '%Y0%' OR fdp.feedDataPointName like '%LRY')
AND fdp.feedDataPointName not like '%Q%'


IF OBJECT_ID ('TEMPDB..#GYANFEEDFY0NEG') IS NOT NULL DROP TABLE #GYANFEEDFY0NEG
SELECT DISTINCT * INTO #GYANFEEDFY0NEG FROM #GYANFEEDFY0 WHERE feedDataPointValue<0

---SELECT * FROM #GYANFEEDFY0NEG

IF OBJECT_ID ('TEMPDB..#GYANFINAL') IS NOT NULL DROP TABLE #GYANFINAL
SELECT CIM.COMPANYNAME,RCT.feedName AS ContributorName,K.*,KE.feedDataPointName,KE.feedDataPointValue AS EPSACTUALVALUE
INTO #GYANFINAL FROM #GYANCAGR K
INNER JOIN #GYANFEEDFY0NEG KE ON K.COMPANYID = KE.COMPANYID AND K.feedFileId=KE.feedFileId
INNER JOIN COMPANYMASTER.DBO.COMPANYINFOMASTER CIM ON CIM.CIQCOMPANYID = K.COMPANYID
INNER JOIN Estimatesfeed.dbo.Feed_tbl RCT ON RCT.RESEARCHCONTRIBUTORID = K.RESEARCHCONTRIBUTORID



SELECT DISTINCT * FROM #GYANFINAL