USE ESTIMATES

IF OBJECT_ID ('TEMPDB..#SSKMINACTIVECOMPANIES') IS NOT NULL DROP TABLE #SSKMINACTIVECOMPANIES
SELECT DISTINCT ED.VERSIONID,ED.FEEDFILEID,ED.COMPANYID,EFFECTIVEDATE,TODATE,ED.RESEARCHCONTRIBUTORID,EDND.DATAITEMID,CS.COMPANYSTATUSTYPEID,COMPANYSTATUSTYPENAME,COMPANYTYPENAME,ed.estimateperiodid,ED.accountingStandardId,ED.tradingItemId,ED.parentFlag INTO #SSKMINACTIVECOMPANIES
  FROM ESTIMATEDETAIL_TBL ED (NOLOCK)
--INNER JOIN ESTIMATEDETAILIDDATA_TBL EDID ON ED.ESTIMATEDETAILID = EDID.ESTIMATEDETAILID
INNER JOIN ESTIMATEDETAILNUMERICDATA_TBL EDND (NOLOCK) ON ED.ESTIMATEDETAILID = EDND.ESTIMATEDETAILID
INNER JOIN ESTIMATEPERIOD_TBL EP (NOLOCK) ON ED.ESTIMATEPERIODID = EP.ESTIMATEPERIODID
LEFT JOIN COMPARISONDATA.DBO.COMPANY_TBL C (NOLOCK) ON C.COMPANYID = ED.COMPANYID
INNER JOIN COMPARISONDATA.DBO.COMPANYSTATUSTYPE_TBL CS (NOLOCK) ON C.COMPANYSTATUSTYPEID = CS.COMPANYSTATUSTYPEID
INNER JOIN COMPARISONDATA.DBO.COMPANYTYPE_TBL CT (NOLOCK) ON CT.COMPANYTYPEID = C.COMPANYTYPEID
INNER JOIN DataItemMaster_vw dimv ON DIMV.dataItemID = EDND.dataItemId
--INNER JOIN DS_DOCUMENTSREADYFORPLATFORM_VW DP (NOLOCK) ON DP.COMPANYID =ED.COMPANYID AND (DP.FEEDFILEID =ED.FEEDFILEID OR DP.VERSIONID = ED.VERSIONID)
--INNER JOIN COMPANYMASTER.DBO.COMPANYSTATUSTYPE_TBL CST ON CST.COMPANYSTATUSTYPEID = CRR.COMPANYSTATUSTYPEID
--INNER JOIN COMPANYMASTER.DBO.COMPANYRESEARCH_TMP CRT ON CRT.COMPANYTYPEID = CRR.COMPANYTYPEID

WHERE COMPANYTYPENAME LIKE '%PRIVATE%'
--WHERE COMPANYSTATUSTYPENAME = 'ACQUIRED'
AND ACTUALIZEDDATE IS NULL
AND TODATE > GETDATE ()
AND PERIODENDDATE > GETDATE () - 200
AND EFFECTIVEDATE < getdate () - 100
AND dimv.flagEAG = 'E'
--AND ED.COMPANYID IN (878281,191884,34473,398377,47411570,2444394,32454463,23887314,307746,349973,536542,881888,20986700,20991211,22384763,49756812,126696264,288355,875610,3661218,10757340,20344645,110000857,878565,881034,12962128,30086407,59318861,20704162,9170732,20334479)
--AND CONTRIBUTORSHORTNAME LIKE '%EUROBANK EFG SECURITIES SA%'
--AND EDND.dataItemId = 21626

--SELECT DISTINCT * FROM #SSKMINACTIVECOMPANIES

--GROUP BY VERSIONID,FEEDFILEID,ED.COMPANYID,EFFECTIVEDATE,PERIODENDDATE,TODATE,ACTUALIZEDDATE,CONTRIBUTORSHORTNAME

IF OBJECT_ID ('TEMPDB..#01') IS NOT NULL DROP TABLE #01
SELECT S.COMPANYID,cim.CompanyName,rct.contributorShortName,S.RESEARCHCONTRIBUTORID,COMPANYSTATUSTYPENAME,COMPANYTYPENAME,COUNT (S.RESEARCHCONTRIBUTORID) AS NOOFRECORDS
INTO #01 FROM #SSKMINACTIVECOMPANIES S
LEFT JOIN CompanyMaster.DBO.CompanyInfoMaster cim ON CIM.CIQCompanyId = S.COMPANYID
INNER JOIN ComparisonData.DBO.ResearchContributor_tbl rct ON RCT.researchContributorId = S.researchContributorId
where EFFECTIVEDATE < getdate () - 100
GROUP BY S.COMPANYID,S.RESEARCHCONTRIBUTORID,COMPANYSTATUSTYPENAME,COMPANYTYPENAME,cim.CompanyName,rct.contributorShortName
ORDER BY NOOFRECORDS DESC

IF OBJECT_ID ('TEMPDB..#02') IS NOT NULL DROP TABLE #02
SELECT S.COMPANYID,cim.CompanyName,COUNT (S.RESEARCHCONTRIBUTORID) AS NOOFRECORDS INTO #02 FROM #SSKMINACTIVECOMPANIES S
LEFT JOIN CompanyMaster.DBO.CompanyInfoMaster cim ON CIM.CIQCompanyId = S.COMPANYID
where EFFECTIVEDATE < getdate () - 100
GROUP BY S.COMPANYID,cim.CompanyName
ORDER BY NOOFRECORDS DESC

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------


IF OBJECT_ID ('TEMPDB..#SSKMACQUIREDCOMPANIES') IS NOT NULL DROP TABLE #SSKMACQUIREDCOMPANIES
SELECT DISTINCT ED.VERSIONID,ED.FEEDFILEID,ED.COMPANYID,EFFECTIVEDATE,TODATE,ED.RESEARCHCONTRIBUTORID,EDND.DATAITEMID,CS.COMPANYSTATUSTYPEID,COMPANYSTATUSTYPENAME,COMPANYTYPENAME,ED.ESTIMATEPERIODID,ED.ACCOUNTINGSTANDARDID,ED.TRADINGITEMID,ED.PARENTFLAG INTO #SSKMACQUIREDCOMPANIES
  FROM ESTIMATEDETAIL_TBL ED (NOLOCK)
--INNER JOIN ESTIMATEDETAILIDDATA_TBL EDID ON ED.ESTIMATEDETAILID = EDID.ESTIMATEDETAILID
INNER JOIN ESTIMATEDETAILNUMERICDATA_TBL EDND (NOLOCK) ON ED.ESTIMATEDETAILID = EDND.ESTIMATEDETAILID
INNER JOIN ESTIMATEPERIOD_TBL EP (NOLOCK) ON ED.ESTIMATEPERIODID = EP.ESTIMATEPERIODID
LEFT JOIN COMPARISONDATA.DBO.COMPANY_TBL C (NOLOCK) ON C.COMPANYID = ED.COMPANYID
INNER JOIN COMPARISONDATA.DBO.COMPANYSTATUSTYPE_TBL CS (NOLOCK) ON C.COMPANYSTATUSTYPEID = CS.COMPANYSTATUSTYPEID
INNER JOIN COMPARISONDATA.DBO.COMPANYTYPE_TBL CT (NOLOCK) ON CT.COMPANYTYPEID = C.COMPANYTYPEID
INNER JOIN DataItemMaster_vw dimv ON DIMV.dataItemID = EDND.dataItemId
--INNER JOIN DS_DOCUMENTSREADYFORPLATFORM_VW DP (NOLOCK) ON DP.COMPANYID =ED.COMPANYID AND (DP.FEEDFILEID =ED.FEEDFILEID OR DP.VERSIONID = ED.VERSIONID)
--INNER JOIN COMPANYMASTER.DBO.COMPANYSTATUSTYPE_TBL CST ON CST.COMPANYSTATUSTYPEID = CRR.COMPANYSTATUSTYPEID
--INNER JOIN COMPANYMASTER.DBO.COMPANYRESEARCH_TMP CRT ON CRT.COMPANYTYPEID = CRR.COMPANYTYPEID

--WHERE COMPANYTYPENAME LIKE '%PRIVATE%'
WHERE COMPANYSTATUSTYPENAME = 'ACQUIRED'
AND COMPANYTYPENAME NOT LIKE '%PRIVATE%'
AND ACTUALIZEDDATE IS NULL
AND TODATE > GETDATE ()
AND PERIODENDDATE > GETDATE () - 200
AND EFFECTIVEDATE < GETDATE () - 100
AND dimv.flagEAG = 'E'
--AND ED.COMPANYID IN (878281,191884,34473,398377,47411570,2444394,32454463,23887314,307746,349973,536542,881888,20986700,20991211,22384763,49756812,126696264,288355,875610,3661218,10757340,20344645,110000857,878565,881034,12962128,30086407,59318861,20704162,9170732,20334479)
--AND CONTRIBUTORSHORTNAME LIKE '%EUROBANK EFG SECURITIES SA%'
--AND EDND.DATAITEMID = 21626

--SELECT DISTINCT * FROM #SSKMINACTIVECOMPANIES

--GROUP BY VERSIONID,FEEDFILEID,ED.COMPANYID,EFFECTIVEDATE,PERIODENDDATE,TODATE,ACTUALIZEDDATE,CONTRIBUTORSHORTNAME

IF OBJECT_ID ('TEMPDB..#03') IS NOT NULL DROP TABLE #03
SELECT S.COMPANYID,CIM.COMPANYNAME,RCT.CONTRIBUTORSHORTNAME,S.RESEARCHCONTRIBUTORID,COMPANYSTATUSTYPENAME,COMPANYTYPENAME,COUNT (S.RESEARCHCONTRIBUTORID) AS NOOFRECORDS
INTO #03 FROM #SSKMACQUIREDCOMPANIES S
LEFT JOIN COMPANYMASTER.DBO.COMPANYINFOMASTER CIM ON CIM.CIQCOMPANYID = S.COMPANYID
INNER JOIN COMPARISONDATA.DBO.RESEARCHCONTRIBUTOR_TBL RCT ON RCT.RESEARCHCONTRIBUTORID = S.RESEARCHCONTRIBUTORID
WHERE EFFECTIVEDATE < GETDATE () - 100
GROUP BY S.COMPANYID,S.RESEARCHCONTRIBUTORID,COMPANYSTATUSTYPENAME,COMPANYTYPENAME,CIM.COMPANYNAME,RCT.CONTRIBUTORSHORTNAME
ORDER BY NOOFRECORDS DESC

IF OBJECT_ID ('TEMPDB..#04') IS NOT NULL DROP TABLE #04
SELECT S.COMPANYID,CIM.COMPANYNAME,COUNT (S.RESEARCHCONTRIBUTORID) AS NOOFRECORDS INTO #04 FROM #SSKMACQUIREDCOMPANIES S
LEFT JOIN COMPANYMASTER.DBO.COMPANYINFOMASTER CIM ON CIM.CIQCOMPANYID = S.COMPANYID
WHERE EFFECTIVEDATE < GETDATE () - 100
GROUP BY S.COMPANYID,CIM.COMPANYNAME
ORDER BY NOOFRECORDS DESC

SELECT DISTINCT * FROM #SSKMINACTIVECOMPANIES
UNION ALL
SELECT DISTINCT * FROM #SSKMACQUIREDCOMPANIES

