USE  Pathfinder
DECLARE @frDate DATETIME, @toDate DATETIME 
SET @frDate = '2023-08-01 06:00:00.000'  --Convert(varchar(10),getdate() -10,101)  
SET @toDate = '2023-09-01 06:00:00.000'  --Convert(varchar(10),getdate()+0,101) 

IF OBJECT_ID ('TEMPDB..#Pathfinder') IS NOT NULL DROP TABLE #Pathfinder
SELECT DISTINCT P.KEYPERSON,P.LOGINNAME,IPS.KEYPROCESSSTREAM,IPS.STREAMNAME , IPI.PROCESSINSTANCEAPPIANID ,TASKINSTANCEBEGUN=TI.TASKINSTANCEBEGUN + '5:30',ti.TaskInstanceDuration,
TASKINSTANCECOMPLETED=TI.TASKINSTANCECOMPLETED + '5:30',TI.TASKINSTANCEEFFORT,TI.EXPECTEDTASKEFFORT ,IPI.PROCESSWORKUNITS,TI.SNLANALYSTTASKENTRY,PN.INTERNALNOTES,PDV.FIELDIDENTIFIER,
PDV.PROCESSFIELDVALUE INTO #Pathfinder FROM PROCESSINSTANCE IPI
INNER JOIN PROCESSSTREAM IPS ON IPI.KEYPROCESSSTREAM = IPS.KEYPROCESSSTREAM AND IPS.UPDOPERATION < 2
INNER JOIN DBO.PROCESSSTREAMGROUP PG ON PG.KEYPROCESSSTREAM=IPS.KEYPROCESSSTREAM
INNER JOIN TASKINSTANCE TI ON IPI.KEYPROCESSINSTANCE = TI.KEYPROCESSINSTANCE AND  TI.UPDOPERATION < 2
INNER JOIN DBO.PROCESSDATAVALUE PDV ON PDV.KEYPROCESSINSTANCE=IPI.KEYPROCESSINSTANCE
LEFT JOIN DBO.PROCESSNOTES PN ON PN.KEYPROCESSINSTANCE=IPI.KEYPROCESSINSTANCE LEFT JOIN InternalUseOnly.DBO.EMPLOYEE P ON TI.KEYPERSON = P.KEYPERSON
WHERE IPI.UPDOPERATION < 2 AND TASKINSTANCECOMPLETED+'5:30' >= @frDate  AND TASKINSTANCECOMPLETED+'5:30' <= @toDate AND IPS.KEYDEPARTMENT = 143 
AND IPS.KEYPROCESSSTREAM in (22264,22265,53181) 

--SELECT * FROM #Pathfinder 

IF OBJECT_ID ('TEMPDB..#Stats') IS NOT NULL DROP TABLE #Stats
SELECT DISTINCT * INTO #Stats FROM 
(SELECT KEYPERSON, LOGINNAME,KEYPROCESSSTREAM,STREAMNAME,PROCESSINSTANCEAPPIANID ,TASKINSTANCEBEGUN,TASKINSTANCECOMPLETED,TASKINSTANCEEFFORT,EXPECTEDTASKEFFORT,
PROCESSWORKUNITS,SNLANALYSTTASKENTRY,INTERNALNOTES,FIELDIDENTIFIER , PROCESSFIELDVALUE FROM #Pathfinder)AS PathSOURCE 
PIVOT ( MAX (PROCESSFIELDVALUE) FOR FIELDIDENTIFIER IN (Taskname,Records))AS PathPIVOT 


--SELECT * FROM #Stats WHERE SPGMIEIN=710819850
 

IF OBJECT_ID('tempdb..#pfjobcount') IS NOT NULL DROP TABLE #pfjobcount
SELECT DISTINCT KEYPERSON,loginName,COUNT(PROCESSINSTANCEAPPIANID) Job_Count INTO #pfjobcount FROM #Stats
GROUP BY KEYPERSON,loginName

--SELECT * FROM #pfjobcount WHERE SPGMIEIN=710819850
 

IF OBJECT_ID ('TEMPDB..#22264') IS NOT NULL DROP TABLE #22264
SELECT DISTINCT KEYPERSON, LOGINNAME,KEYPROCESSSTREAM,STREAMNAME,PROCESSINSTANCEAPPIANID,TaskInstanceBegun,TASKINSTANCECOMPLETED,ProcessWorkUnits,Taskname,
SNLANALYSTTASKENTRY,CASE WHEN ISNUMERIC(Records) = 1 OR Records IS NULL THEN CAST(Records AS INT) ELSE NULL END AS records,INTERNALNOTES comment_note,
CASE SNLANALYSTTASKENTRY WHEN 0 THEN 'Data Not Update'WHEN 1 THEN 'Data Updated' ELSE 'Previous update' END AS User_input,
TASKINSTANCEEFFORT AS timetaken,EXPECTEDTASKEFFORT AS Targettime INTO #22264 FROM #Stats

--SELECT * FROM #22264 WHERE SPGMIEIN=710822997
 

IF OBJECT_ID('tempdb..#e') IS NOT NULL DROP TABLE #e
SELECT DISTINCT CONVERT(VARCHAR(10),TaskInstanceCompleted -'6:20',101) AS  TASKINSTANCECOMPLETED ,KEYPERSON, LoginName,KeyProcessStream,
StreamName,ProcessInstanceAppianID,TaskInstanceBegun,TaskInstanceCompleted AS TaskInstanceCompleted1,
timetaken,Targettime,ProcessWorkUnits,SNLANALYSTTASKENTRY,TASKINSTANCECOMPLETED AS insertdate,records,
CASE WHEN (KeyProcessStream = 53181) THEN records*0.47 WHEN (KeyProcessStream = 22265) THEN records*1.90 ELSE 3.3 END AS Jobscount 
INTO #e FROM #22264 WHERE KeyProcessStream in (22264,22265,53181) 

--SELECT * FROM #e WHERE loginname='vvallabhapuram'
 

------------IR Alert Query-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 

IF OBJECT_ID ('TEMPDB..#Pathfinder1') IS NOT NULL DROP TABLE #Pathfinder1
SELECT DISTINCT P.KEYPERSON, P.LOGINNAME,IPS.KEYPROCESSSTREAM,IPS.STREAMNAME , IPI.PROCESSINSTANCEAPPIANID ,
TASKINSTANCEBEGUN=TI.TASKINSTANCEBEGUN + '5:30',ti.TaskInstanceDuration,TASKINSTANCECOMPLETED=TI.TASKINSTANCECOMPLETED + '5:30',
TI.TASKINSTANCEEFFORT,TI.EXPECTEDTASKEFFORT ,IPI.PROCESSWORKUNITS,TI.SNLANALYSTTASKENTRY,PN.INTERNALNOTES,PDV.FIELDIDENTIFIER,
PDV.PROCESSFIELDVALUE INTO #Pathfinder1 FROM PROCESSINSTANCE IPI
INNER JOIN PROCESSSTREAM IPS ON IPI.KEYPROCESSSTREAM = IPS.KEYPROCESSSTREAM AND IPS.UPDOPERATION < 2
LEFT JOIN DBO.PROCESSSTREAMGROUP PG ON PG.KEYPROCESSSTREAM=IPS.KEYPROCESSSTREAM
INNER JOIN TASKINSTANCE TI ON IPI.KEYPROCESSINSTANCE = TI.KEYPROCESSINSTANCE AND  TI.UPDOPERATION < 2
INNER JOIN DBO.PROCESSDATAVALUE PDV ON PDV.KEYPROCESSINSTANCE=IPI.KEYPROCESSINSTANCE
LEFT JOIN DBO.PROCESSNOTES PN ON PN.KEYPROCESSINSTANCE=IPI.KEYPROCESSINSTANCE 
LEFT JOIN InternalUseOnly.DBO.EMPLOYEE P ON TI.KEYPERSON = P.KEYPERSON
WHERE IPI.UPDOPERATION < 2 AND TASKINSTANCECOMPLETED >= @frDate AND TASKINSTANCECOMPLETED <= @toDate AND IPS.KEYDEPARTMENT = 143 
AND IPS.KEYPROCESSSTREAM IN (53442,53443,53444,53445,53554) --,54867 - client issues

--SELECT * FROM #Pathfinder1 WHERE SPGMIEIN=710819850 and STREAMNAME='Preprocess Research Task'


IF OBJECT_ID ('TEMPDB..#Stats1') IS NOT NULL DROP TABLE #Stats1
SELECT DISTINCT * INTO #Stats1 FROM 
(SELECT KEYPERSON, LOGINNAME,KEYPROCESSSTREAM,STREAMNAME,PROCESSINSTANCEAPPIANID ,TASKINSTANCEBEGUN,TASKINSTANCECOMPLETED,
TASKINSTANCEEFFORT,EXPECTEDTASKEFFORT,PROCESSWORKUNITS,SNLANALYSTTASKENTRY,INTERNALNOTES,FIELDIDENTIFIER ,PROCESSFIELDVALUE FROM #Pathfinder1)AS PathSOURCE 
PIVOT ( MAX (PROCESSFIELDVALUE) FOR FIELDIDENTIFIER IN (Taskname,Records)) AS PathPIVOT 

--SELECT * FROM #Stats1 WHERE SPGMIEIN=710819850
 

IF OBJECT_ID('tempdb..#pfjobcount1') IS NOT NULL DROP TABLE #pfjobcount1
SELECT DISTINCT KEYPERSON,loginName,COUNT(PROCESSINSTANCEAPPIANID) Job_Count INTO #pfjobcount1 FROM #Stats1
GROUP BY KEYPERSON,loginName

--SELECT * FROM #pfjobcount1 WHERE SPGMIEIN=710819850
 

IF OBJECT_ID ('TEMPDB..#222641') IS NOT NULL DROP TABLE #222641
SELECT DISTINCT KEYPERSON, LOGINNAME,KEYPROCESSSTREAM,STREAMNAME,PROCESSINSTANCEAPPIANID,TaskInstanceBegun,TASKINSTANCECOMPLETED,
ProcessWorkUnits,Taskname,SNLANALYSTTASKENTRY,INTERNALNOTES comment_note, 
CASE SNLANALYSTTASKENTRY WHEN 0 THEN 'Data Not Update' WHEN 1 THEN 'Data Updated' ELSE 'Previous update' END AS User_input,
TASKINSTANCEEFFORT AS timetaken,EXPECTEDTASKEFFORT AS Targettime INTO #222641 FROM #Stats1

--SELECT * FROM #222641 WHERE SPGMIEIN=710819850
 

IF OBJECT_ID('tempdb..#e1') IS NOT NULL DROP TABLE #e1
SELECT CONVERT(date,TASKINSTANCECOMPLETED,110) AS TASKINSTANCECOMPLETED ,KEYPERSON, LoginName,KeyProcessStream,StreamName,
ProcessInstanceAppianID,TaskInstanceBegun,TaskInstanceCompleted AS TaskInstanceCompleted1,
CASE WHEN (timetaken>Targettime) THEN Targettime ELSE timetaken END AS final_time,timetaken,Targettime,
SNLANALYSTTASKENTRY,TASKINSTANCECOMPLETED AS insertdate, comment = 'Pathfinder special task' ,comment_note INTO #e1 FROM #222641 
WHERE KEYPERSON IN (752569,752437,751236,752041,752107,751970,752019,752514,751235,751902,751233,750911,751967)

--SELECT * FROM #e1 WHERE SPGMIEIN=710819850


IF OBJECT_ID('tempdb..#e2') IS NOT NULL DROP TABLE #e2
SELECT DISTINCT *,final_time/60 AS Final_Time_Hours,
CASE WHEN KEYPERSON in (751236,751970,752019,752041,752514) THEN 57.1 
WHEN KEYPERSON in (752437,750911,751233,751235,751902,751967,752107,752569) THEN 62.9 END AS Hourly_Targets,
--WHEN KEYPERSON IN (710830358) then 65.7 end Hourly_Targets,
CASE WHEN KEYPERSON IN (751236,751970,752019,752041,752514) THEN (final_time/60)*57.1 
WHEN KEYPERSON IN (752437,750911,751233,751235,751902,751967,752107,752569) THEN (final_time/60)*62.9 END AS Total_Targets
--WHEN KEYPERSON IN (710830358) THEN (final_time/60)*65.7 END AS Total_Targets 
INTO #e2 FROM #e1


--SELECT * FROM #e2 WHERE SPGMIEIN=710819850 

SELECT DISTINCT a.KEYPERSON,a.LoginName,--b.Job_Count Actual_Job_Count, isnull(sum(records),0) Total_Records,
ISNULL(SUM(jobscount),0) AS Total_Jobcount_After_Weights,'QMS PF' AS Process FROM #e a
INNER JOIN #pfjobcount b ON b.KEYPERSON=a.KEYPERSON
GROUP BY a.KEYPERSON,a.loginname
UNION ALL
SELECT DISTINCT a.KEYPERSON,a.LoginName,--b.Job_Count,sum(CAST(Final_Time_Hours AS decimal(18,2))) Final_Time_Hours,--Hourly_Targets,sum(CAST(final_time AS decimal(18,2))) Final_Time_Total,
SUM(CAST(Total_Targets AS decimal(18,2))) AS Total_Targets,'IR Alerts' AS Process FROM #e2 a
INNER JOIN #pfjobcount1 b ON b.KEYPERSON=a.KEYPERSON
GROUP BY a.KEYPERSON,a.LoginName
 

SELECT DISTINCT * FROM #e
SELECT DISTINCT * FROM #e2