--PYTHO,SQL,AZURE DATA FACTORY AND POWER BI ETL DEVELOPER --> GNANESHWAR SRAVANE
USE Pathfinder
DECLARE @frDate DATETIME, @toDate DATETIME 
--SET @frDate = '2019-11-01 06:00:00.000' -- Give From Date here 
--SET @toDate = '2019-11-10 23:59:00.000'-- Give To Date here
IF OBJECT_ID ('TEMPDB..#PFJobDetails') IS NOT NULL DROP TABLE #PFJobDetails
SELECT DISTINCT P.KEYPERSON,P.SPGMIEIN, P.LOGINNAME,IPI.KEYPROCESSSTREAM,IPS.STREAMNAME ,IPI.ProcessInstanceInstantiated,IPI.PROCESSINSTANCEAPPIANID ,TASKINSTANCEBEGUN=TI.TASKINSTANCEBEGUN + '5:30',PFJ.ProcessInstanceTargetDate
,TASKINSTANCECOMPLETED=TI.TASKINSTANCECOMPLETED + '5:30',TI.TASKINSTANCEEFFORT,TI.EXPECTEDTASKEFFORT,IPI.PROCESSWORKUNITS,TI.SNLANALYSTTASKENTRY,IPI.ProcessInstanceDescription INTO #PFJobDetails FROM PROCESSINSTANCE IPI
LEFT JOIN PROCESSSTREAM IPS ON IPI.KEYPROCESSSTREAM = IPS.KEYPROCESSSTREAM
LEFT JOIN TASKINSTANCE TI ON IPI.KEYPROCESSINSTANCE = TI.KEYPROCESSINSTANCE
LEFT JOIN InternalUseOnly.DBO.EMPLOYEE P ON TI.KEYPERSON = P.KEYPERSON
LEFT JOIN PFJobs PFJ ON PFJ.ProcessInstanceAppianID = IPI.ProcessInstanceAppianID
WHERE ((TI.TASKINSTANCEBEGUN BETWEEN GETDATE()-365 AND GETDATE()) OR (IPI.ProcessInstanceInstantiated BETWEEN GETDATE()-365 AND GETDATE()))
AND IPS.KEYPROCESSSTREAM IN (23849)

--SELECT * FROM #PFJobDetails

SELECT DISTINCT KEYPERSON,SPGMIEIN,LOGINNAME,KEYPROCESSSTREAM,STREAMNAME,TASKINSTANCEBEGUN,ProcessInstanceInstantiated,PROCESSINSTANCEDESCRIPTION,PROCESSINSTANCEAPPIANID,TASKINSTANCECOMPLETED,PROCESSINSTANCETARGETDATE, 
SNLANALYSTTASKENTRY FROM #PFJobDetails
ORDER BY TASKINSTANCEBEGUN,ProcessInstanceInstantiated

