USE pathfinder

DECLARE @frdate AS DATETIME,@todate AS DATETIME
SET @frdate='2023-08-29 00:00:00.000'
SET @todate='2023-08-30 23:59:59.999'

IF OBJECT_ID ('TEMPDB..#KRISHNAGYAN') IS NOT NULL DROP TABLE #KRISHNAGYAN
SELECT DISTINCT Convert(varchar(10),(TASKINSTANCECOMPLETED+'5:30')-'6:20',101)  LOGINDATE,P.KEYPERSON,P.SPGMIEIN, P.LOGINNAME,IPS.KEYPROCESSSTREAM,IPS.STREAMNAME, 
ProcessInstanceInstantiated+'5:30'  as INSERTDATE,IPI.PROCESSINSTANCEAPPIANID ,TI.TASKINSTANCEBEGUN+'5:30' as TASKINSTANCEBEGUN ,TI.TASKINSTANCECOMPLETED+'5:30' as TASKINSTANCECOMPLETED
,TI.TASKINSTANCEEFFORT,TI.EXPECTEDTASKEFFORT,CASE WHEN TASKINSTANCEEFFORT<=EXPECTEDTASKEFFORT THEN TASKINSTANCEEFFORT ELSE EXPECTEDTASKEFFORT END AS ACTUALTASKEFFORT,
IPI.PROCESSWORKUNITS,TI.SNLANALYSTTASKENTRY,PDV.FIELDIDENTIFIER,PDV.PROCESSFIELDVALUE
INTO #KRISHNAGYAN FROM PROCESSINSTANCE IPI
INNER JOIN PROCESSSTREAM IPS ON IPI.KEYPROCESSSTREAM = IPS.KEYPROCESSSTREAM AND IPS.UPDOPERATION < 2
INNER JOIN DBO.PROCESSSTREAMGROUP PG ON PG.KEYPROCESSSTREAM=IPS.KEYPROCESSSTREAM
JOIN TASKINSTANCE TI ON IPI.KEYPROCESSINSTANCE = TI.KEYPROCESSINSTANCE AND  TI.UPDOPERATION < 2
JOIN DBO.PROCESSDATAVALUE PDV ON PDV.KEYPROCESSINSTANCE=IPI.KEYPROCESSINSTANCE
LEFT JOIN DBO.PROCESSNOTES PN ON PN.KEYPROCESSINSTANCE=IPI.KEYPROCESSINSTANCE
LEFT JOIN INTERNALUSEONLY. DBO.EMPLOYEE P ON TI.KEYPERSON = P.KEYPERSON
WHERE IPI.UPDOPERATION < 2
AND TI.TASKINSTANCECOMPLETED +'5:30' >= @frdate
AND TI.TASKINSTANCECOMPLETED +'5:30' <= @todate
AND IPS.KEYDEPARTMENT = 143
and P.LOGINNAME in ('jbalasubramanyam','rkurakula', 'nkotha','vvatti', 'avadapalli','hjaldu','rkaturi','abandaru')
--AND SPGMIEIN IN (710831346,710829846,710819856,710821425,710829584,710819860,710829858,710825015,710818702,710829585,810818293,710844749,710844738,710808654,710809484,710820948,710826325,710810028)--Give Employee EIN Number Here 
IF OBJECT_ID ('TEMPDB..#KRISHNAGYANPIVOT') IS NOT NULL DROP TABLE #KRISHNAGYANPIVOT
SELECT DISTINCT * INTO #KRISHNAGYANPIVOT FROM (SELECT LOGINDATE,KEYPERSON,SPGMIEIN, LOGINNAME,KEYPROCESSSTREAM,STREAMNAME,PROCESSINSTANCEAPPIANID ,INSERTDATE,TASKINSTANCEBEGUN,TASKINSTANCECOMPLETED,
TASKINSTANCEEFFORT,EXPECTEDTASKEFFORT,ACTUALTASKEFFORT,PROCESSWORKUNITS,SNLANALYSTTASKENTRY,
CASE WHEN KEYPROCESSSTREAM IN (56777,56785) AND SNLANALYSTTASKENTRY=1 THEN 2.754 WHEN KEYPROCESSSTREAM IN (56777,56785) AND SNLANALYSTTASKENTRY=0 THEN 0.55 ELSE PROCESSWORKUNITS END AS TOTALFILES,
CASE WHEN KEYPROCESSSTREAM IN (56777,56785) AND SNLANALYSTTASKENTRY=1 THEN 2.754*9.375 WHEN KEYPROCESSSTREAM IN (56777,56785) AND SNLANALYSTTASKENTRY=0 THEN 0.55*9.375 ELSE ACTUALTASKEFFORT END AS TOTALMINUTS,
FIELDIDENTIFIER,CAST(PROCESSFIELDVALUE AS VARCHAR(MAX)) PROCESSFIELDVALUE FROM #KRISHNAGYAN)
AS KRISHNASOURCE
PIVOT
(
      MAX (PROCESSFIELDVALUE) FOR FIELDIDENTIFIER IN (COMPANYID,VERSIONID,Task,Description)
)
AS KRISHNAPIVOT 

----Summary Records
SELECT LOGINDATE,LOGINNAME,SUM(TOTALFILES) AS TOTALFILES,SUM(TOTALMINUTS) AS TOTALMINUTS
FROM
#KRISHNAGYANPIVOT
GROUP BY LOGINDATE,LOGINNAME
ORDER BY LOGINDATE

---Total Records
SELECT * FROM #KRISHNAGYANPIVOT ORDER BY LOGINDATE,SPGMIEIN,STREAMNAME 
